var express = require('express')
var router = express.Router()

const {attributeinstances} = require('../modules/attributeinstances/attributeinstances.route.js')
const {attributes} = require('../modules/attributes/attributes.route.js')
const {attributesetinstances} = require('../modules/attributesetinstances/attributesetinstances.route.js')
const {attributesets} = require('../modules/attributesets/attributesets.route.js')
const {attributeuse} = require('../modules/attributeuse/attributeuse.route.js')
const {attributevalues} = require('../modules/attributevalues/attributevalues.route.js')
const {blocations} = require('../modules/blocations/blocations.route.js')
const {businesses} = require('../modules/businesses/businesses.route.js')
const {businesspermission} = require('../modules/businesspermission/businesspermission.route.js')
const {businesstype} = require('../modules/businesstype/businesstype.route.js')
const {cashreconcillation} = require('../modules/cashreconcillation/cashreconcillation.route.js')
const {closedcash} = require('../modules/closedcash/closedcash.route.js')
const {demo} = require('../modules/demo/demo.route.js')
const {grn} = require('../modules/grn/grn.route.js')
const {grnitems} = require('../modules/grnitems/grnitems.route.js')
const {hsncodes} = require('../modules/hsncodes/hsncodes.route.js')
const {mitems} = require('../modules/mitems/mitems.route.js')
const {modifiers} = require('../modules/modifiers/modifiers.route.js')
const {modifiersitems} = require('../modules/modifiersitems/modifiersitems.route.js')
const {modifieruse} = require('../modules/modifieruse/modifieruse.route.js')
const {nbroles} = require('../modules/nbroles/nbroles.route.js')
const {newsletters} = require('../modules/newsletters/newsletters.route.js')
const {nrole} = require('../modules/nrole/nrole.route.js')
const {nroleuserslocations} = require('../modules/nroleuserslocations/nroleuserslocations.route.js')
const {productcategories} = require('../modules/productcategories/productcategories.route.js')
const {productkeys} = require('../modules/productkeys/productkeys.route.js')
const {products} = require('../modules/products/products.route.js')
const {productstaxes} = require('../modules/productstaxes/productstaxes.route.js')
const {purchaseitems} = require('../modules/purchaseitems/purchaseitems.route.js')
const {purchases} = require('../modules/purchases/purchases.route.js')
const {qr} = require('../modules/qr/qr.route.js')
const {receipts} = require('../modules/receipts/receipts.route.js')
const {rights} = require('../modules/rights/rights.route.js')
const {roles} = require('../modules/roles/roles.route.js')
const {rolestablepermissions} = require('../modules/rolestablepermissions/rolestablepermissions.route.js')
const {stockcurrent} = require('../modules/stockcurrent/stockcurrent.route.js')
const {stockdiary} = require('../modules/stockdiary/stockdiary.route.js')
const {stocklevel} = require('../modules/stocklevel/stocklevel.route.js')
const {tables} = require('../modules/tables/tables.route.js')
const {tablespermissions} = require('../modules/tablespermissions/tablespermissions.route.js')
const {taxcategories} = require('../modules/taxcategories/taxcategories.route.js')
const {taxes} = require('../modules/taxes/taxes.route.js')
const {taxlines} = require('../modules/taxlines/taxlines.route.js')
const {ticketlines} = require('../modules/ticketlines/ticketlines.route.js')
const {tickets} = require('../modules/tickets/tickets.route.js')
const {tickettypes} = require('../modules/tickettypes/tickettypes.route.js')
const {transactions} = require('../modules/transactions/transactions.route.js')
const {transactionstatus} = require('../modules/transactionstatus/transactionstatus.route.js')
const {transactiontypes} = require('../modules/transactiontypes/transactiontypes.route.js')
const {uomconversions} = require('../modules/uomconversions/uomconversions.route.js')
const {uoms} = require('../modules/uoms/uoms.route.js')
const {users} = require('../modules/users/users.route.js')
const {userslocations} = require('../modules/userslocations/userslocations.route.js')
const {usersroles} = require('../modules/usersroles/usersroles.route.js')
const {usertypes} = require('../modules/usertypes/usertypes.route.js')
const {vendors} = require('../modules/vendors/vendors.route.js')


router.use('/', attributeinstances)
router.use('/', attributes)
router.use('/', attributesetinstances)
router.use('/', attributesets)
router.use('/', attributeuse)
router.use('/', attributevalues)
router.use('/', blocations)
router.use('/', businesses)
router.use('/', businesspermission)
router.use('/', businesstype)
router.use('/', cashreconcillation)
router.use('/', closedcash)
router.use('/', demo)
router.use('/', grn)
router.use('/', grnitems)
router.use('/', hsncodes)
router.use('/', mitems)
router.use('/', modifiers)
router.use('/', modifiersitems)
router.use('/', modifieruse)
router.use('/', nbroles)
router.use('/', newsletters)
router.use('/', nrole)
router.use('/', nroleuserslocations)
router.use('/', productcategories)
router.use('/', productkeys)
router.use('/', products)
router.use('/', productstaxes)
router.use('/', purchaseitems)
router.use('/', purchases)
router.use('/', qr)
router.use('/', receipts)
router.use('/', rights)
router.use('/', roles)
router.use('/', rolestablepermissions)
router.use('/', stockcurrent)
router.use('/', stockdiary)
router.use('/', stocklevel)
router.use('/', tables)
router.use('/', tablespermissions)
router.use('/', taxcategories)
router.use('/', taxes)
router.use('/', taxlines)
router.use('/', ticketlines)
router.use('/', tickets)
router.use('/', tickettypes)
router.use('/', transactions)
router.use('/', transactionstatus)
router.use('/', transactiontypes)
router.use('/', uomconversions)
router.use('/', uoms)
router.use('/', users)
router.use('/', userslocations)
router.use('/', usersroles)
router.use('/', usertypes)
router.use('/', vendors)
   
    
module.exports = router